---
- name: Deploy Static Website
  hosts: prod
  become: true

  tasks:
    - name: Copy Nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

    - name: Copy static website content
      synchronize:
        src: /ansible/static-website/
        dest: /usr/share/nginx/html/
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted
